version: '3'
networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: '33.33.0.0/16'
services:
  postgres:
    image: postgres:latest
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: '123456'
    networks:
      app_network:
        ipv4_address: 33.33.0.8

  #Application Service
  api:
    build:
      context: .
      dockerfile: /apps/api/Dockerfile
    ports:
      - '13000:3000'
    environment:
      - DATABASE_URL=localhost
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      app_network:
        ipv4_address: 33.33.0.4
